package com.fleetops.service.report;

import com.fleetops.util.SecurityUtils;
import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.io.ByteArrayOutputStream;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

public abstract class AbstractReportGenerator<T, F> implements ReportGenerator {

    protected abstract String getReportTitle();
    protected abstract String[] getHeaders();
    protected abstract List<T> fetchData(F filterCriteria);
    protected abstract String[] getRowData(T item);
    protected abstract String getAppliedFiltersString(F filterCriteria);

    @Override
    @SuppressWarnings("unchecked")
    public byte[] generatePdf(Object filterCriteria) {
        F filters = (F) filterCriteria;
        List<T> data = fetchData(filters);

        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            Document document = new Document(PageSize.A4.rotate());
            PdfWriter.getInstance(document, baos);
            document.open();

            // Meta Info
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
            Paragraph title = new Paragraph("FleetOps Enterprise - " + getReportTitle(), titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);

            document.add(new Paragraph(" "));

            Font metaFont = FontFactory.getFont(FontFactory.HELVETICA, 10);
            document.add(new Paragraph("Generated By: " + SecurityUtils.getCurrentUsername(), metaFont));
            document.add(new Paragraph("Generated On: " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")), metaFont));
            document.add(new Paragraph("Applied Filters: " + getAppliedFiltersString(filters), metaFont));
            document.add(new Paragraph("Version: FleetOps Enterprise v1.0", metaFont));

            document.add(new Paragraph(" "));

            // Table
            String[] headers = getHeaders();
            PdfPTable table = new PdfPTable(headers.length);
            table.setWidthPercentage(100);

            Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11);
            for (String header : headers) {
                PdfPCell cell = new PdfPCell(new Phrase(header, headerFont));
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell.setBackgroundColor(new java.awt.Color(230, 230, 230));
                cell.setPadding(5);
                table.addCell(cell);
            }

            Font rowFont = FontFactory.getFont(FontFactory.HELVETICA, 10);
            for (T item : data) {
                String[] rowData = getRowData(item);
                for (String val : rowData) {
                    PdfPCell cell = new PdfPCell(new Phrase(val != null ? val : "", rowFont));
                    cell.setPadding(4);
                    table.addCell(cell);
                }
            }

            document.add(table);
            document.close();
            return baos.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Error generating PDF report", e);
        }
    }

    @Override
    @SuppressWarnings("unchecked")
    public byte[] generateExcel(Object filterCriteria) {
        F filters = (F) filterCriteria;
        List<T> data = fetchData(filters);

        try (Workbook workbook = new XSSFWorkbook(); ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            Sheet sheet = workbook.createSheet(getReportTitle());

            // Meta Info
            Row titleRow = sheet.createRow(0);
            Cell titleCell = titleRow.createCell(0);
            titleCell.setCellValue("FleetOps Enterprise - " + getReportTitle());

            sheet.createRow(1).createCell(0).setCellValue("Generated By: " + SecurityUtils.getCurrentUsername());
            sheet.createRow(2).createCell(0).setCellValue("Generated On: " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
            sheet.createRow(3).createCell(0).setCellValue("Applied Filters: " + getAppliedFiltersString(filters));
            sheet.createRow(4).createCell(0).setCellValue("Version: FleetOps Enterprise v1.0");

            // Headers
            Row headerRow = sheet.createRow(6);
            String[] headers = getHeaders();
            CellStyle headerStyle = workbook.createCellStyle();
            org.apache.poi.ss.usermodel.Font headerFont = workbook.createFont();
            headerFont.setBold(true);
            headerStyle.setFont(headerFont);

            for (int i = 0; i < headers.length; i++) {
                Cell cell = headerRow.createCell(i);
                cell.setCellValue(headers[i]);
                cell.setCellStyle(headerStyle);
            }

            // Data
            int rowIdx = 7;
            for (T item : data) {
                Row row = sheet.createRow(rowIdx++);
                String[] rowData = getRowData(item);
                for (int i = 0; i < rowData.length; i++) {
                    row.createCell(i).setCellValue(rowData[i] != null ? rowData[i] : "");
                }
            }

            for (int i = 0; i < headers.length; i++) {
                sheet.autoSizeColumn(i);
            }

            workbook.write(baos);
            return baos.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Error generating Excel report", e);
        }
    }

    @Override
    @SuppressWarnings("unchecked")
    public byte[] generateCsv(Object filterCriteria) {
        F filters = (F) filterCriteria;
        List<T> data = fetchData(filters);

        try (ByteArrayOutputStream baos = new ByteArrayOutputStream();
             PrintWriter writer = new PrintWriter(baos, true, StandardCharsets.UTF_8)) {

            // CSV BOM for Excel compatibility
            baos.write(239);
            baos.write(187);
            baos.write(191);

            // Meta Info
            writer.println("FleetOps Enterprise - " + getReportTitle());
            writer.println("Generated By," + SecurityUtils.getCurrentUsername());
            writer.println("Generated On," + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
            writer.println("Applied Filters,\"" + getAppliedFiltersString(filters).replace("\"", "\"\"") + "\"");
            writer.println("Version,FleetOps Enterprise v1.0");
            writer.println();

            // Headers
            String[] headers = getHeaders();
            writer.println(String.join(",", escapeCsvValues(headers)));

            // Data
            for (T item : data) {
                writer.println(String.join(",", escapeCsvValues(getRowData(item))));
            }

            return baos.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Error generating CSV report", e);
        }
    }
    
    private String[] escapeCsvValues(String[] values) {
        String[] escaped = new String[values.length];
        for(int i=0; i<values.length; i++) {
            String val = values[i] == null ? "" : values[i];
            if (val.contains(",") || val.contains("\"") || val.contains("\n")) {
                val = "\"" + val.replace("\"", "\"\"") + "\"";
            }
            escaped[i] = val;
        }
        return escaped;
    }
}
