spring.application.name=fleetops

spring.datasource.url=jdbc:mysql://localhost:3306/fleetops
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=9090
logging.level.org.hibernate=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
